<?php
namespace Application\Handler;


use Coffeeman\Application\Command\SumSportsmanWorkouts;
use Coffeeman\Application\Handler\SumSportsmanWorkoutsHandler;
use Coffeeman\Infrastructure\Domain\Workout\Dbal\DbalWorkoutQuery;
use Coffeeman\Infrastructure\Domain\Workout\Dbal\DbalWorkoutTypeQuery;
use Tests\Unit\CoffeemanDatabase;

class SumSportsmanWorkoutsHandlerTest extends \Codeception\Test\Unit
{
    public function _after()
    {
        session_unset();
        parent::_after(); // TODO: Change the autogenerated stub
    }

    public function testHandlingShouldPassWithCorrectUserId()
    {
        @session_start();
        $command = new SumSportsmanWorkouts('d6e66f53-843b-4dab-bb64-6faa91e5928e');

        $sumSportsmanWorkoutsHandler = new SumSportsmanWorkoutsHandler(new DbalWorkoutQuery(CoffeemanDatabase::getConnection()), new DbalWorkoutTypeQuery(CoffeemanDatabase::getConnection()));
        $sumSportsmanWorkoutsHandler->handle($command);

        $this->assertTrue(isset($_SESSION['summedSportsmanWorkouts']));
    }

    /**
     * @expectedException \InvalidArgumentException
     */
    public function testHandlingShouldReturnAnExceptionWithIncorrectUserId()
    {
        $command = new SumSportsmanWorkouts('incorrect-id');

        $sumSportsmanWorkoutsHandler = new SumSportsmanWorkoutsHandler(new DbalWorkoutQuery(CoffeemanDatabase::getConnection()), new DbalWorkoutTypeQuery(CoffeemanDatabase::getConnection()));
        $sumSportsmanWorkoutsHandler->handle($command);
    }

}