build:
    environment:
        hosts:
            local.dev: '127.0.0.1'
        php:
          - '7.1'

        before_script:
          - composer self-update
          - composer install --prefer-source

        script: vendor/bin/codecept run
    project_setup:
        before:
            - mysql -uroot -e "SET GLOBAL sql_mode = 'STRICT_ALL_TABLES'"
        override: []
        after: []