build:
    environment:
        hosts:
            local.dev: '127.0.0.1'
        php:
            version: 7.1
    project_setup:
        before:
            - mysql -e "CREATE DATABASE coffeeman_test"
            - mysql -u root coffeeman_test < tests/_data/dump.sql
        override: []
        after: []
