language: php

php:
  - '7.1'

services:
  - mysql

before_script:
  - composer self-update
  - composer install --prefer-source

before_install:
  - mysql -e 'CREATE DATABASE coffeeman_test;'

script: vendor/bin/codecept run
