<<<<<<< HEAD
<?php  //[STAMP] 525773c605ae90ee294676d694928c82
=======
<?php  //[STAMP] a16f3e712731aec8870716396d754df2
>>>>>>> 994943ed86b3589b29b84e875488cc7a736bed25
namespace _generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

use Helper\Functional;

trait FunctionalTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
