<?php
namespace Application\Service;

use Coffeeman\Application\Service\CheckStrategy;
use Coffeeman\Application\Service\IsUserSignedIn;

class CheckStrategyTest extends \Codeception\Test\Unit
{
    public function tearDown()
    {
        session_unset();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testIsCheckMethodReturnFalseIfUserIsNotSignedIn()
    {
        $check = new CheckStrategy(new IsUserSignedIn());

        $resultOfCheck = $check->check();

        $this->assertFalse($resultOfCheck);
    }

    public function testIsCheckMethodReturnTrueIfUserIsSignedIn()
    {
        @session_start();
        $_SESSION['user'] = 'Test';

        $check = new CheckStrategy(new IsUserSignedIn());

        $resultOfCheck = $check->check();

        $this->assertTrue($resultOfCheck);
    }
}