<?php
namespace Application\Service;

use Coffeeman\Infrastructure\Domain\Check\IsUserSignedIn;

class IsUserSignedInTest extends \Codeception\Test\Unit
{
    public function tearDown()
    {
        session_unset();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testIsCheckMethodReturnFalseIfUserIsNotSignedIn()
    {
        $isUserSignedIn = new IsUserSignedIn();

        $resultOfCheck = $isUserSignedIn->check();

        $this->assertFalse($resultOfCheck);
    }

    public function testIsCheckMethodReturnTrueIfUserIsSignedIn()
    {
        @session_start();
        $_SESSION['user'] = 'Test';

        $isUserSignedIn = new IsUserSignedIn();

        $resultOfCheck = $isUserSignedIn->check();

        $this->assertTrue($resultOfCheck);
    }
}