<?php
namespace Application\Service;


use Coffeeman\Application\Service\SignOutUser;

class SignOutUserTest extends \Codeception\Test\Unit
{
    public function tearDown()
    {
        session_unset();

        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testSigningOutUserDeletingUserSessionAndSummedSportsmanWorkouts()
    {
        @session_start();
        $_SESSION['user'] = 'Test';
        $_SESSION['summedSportsmanWorkouts'] = ['burnedCalories' => 600];

        $signOutUser = new SignOutUser();
        $signOutUser->signOut();

        $this->assertFalse(isset($_SESSION['user']));
        $this->assertFalse(isset($_SESSION['summedSportsmanWorkouts']));
    }
}