<?php
namespace Application\Service;


use Coffeeman\Application\Service\SumSportsmanWorkoutsApplicationService;
use Coffeeman\Application\SimpleCommandBus;
use Doctrine\DBAL\Connection;
use Doctrine\DBAL\Driver\PDOMySql\Driver;
use Tests\Unit\CoffeemanDatabase;

class SumSportsmanWorkoutsApplicationServiceTest extends \Codeception\Test\Unit
{
    public function _after()
    {
        session_unset();
        parent::_after(); // TODO: Change the autogenerated stub
    }

    public function testPassingRightDataSumSportsmanWorkouts()
    {
        @session_start();
        $expected = [
            'burnedCalories' => 1670,
            'sportsmanId' => 'd6e66f53-843b-4dab-bb64-6faa91e5928e',
            'mostFrequentWorkoutType' => 'HIIT'
        ];

        $sumSportsmanWorkout = new SumSportsmanWorkoutsApplicationService(new SimpleCommandBus(), new Connection(CoffeemanDatabase::getDbParams(), new Driver()), 'd6e66f53-843b-4dab-bb64-6faa91e5928e');
        $sumSportsmanWorkout->sumSportsmanWorkouts();

        $this->assertEquals($expected, $_SESSION['user']['summedSportsmanWorkouts']);
    }

    /**
     * @expectedException \InvalidArgumentException
     */
    public function testPassingIncorrectUserIdShouldReturnAnException()
    {
        $sumSportsmanWorkout = new SumSportsmanWorkoutsApplicationService(new SimpleCommandBus(), new Connection(CoffeemanDatabase::getDbParams(), new Driver()), 'incorrect-id');
        $sumSportsmanWorkout->sumSportsmanWorkouts();
    }
}